# Generated by Django 4.2.30 on 2026-05-11 21:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TailorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(default='University of Zululand', max_length=200)),
                ('bio', models.TextField(blank=True)),
                ('avatar_initials', models.CharField(blank=True, max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EstimateHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('garment', models.CharField(choices=[('Blouse', 'Blouse'), ('Coat', 'Coat'), ('Dress', 'Dress'), ('Hoodie', 'Hoodie'), ('Jacket', 'Jacket'), ('Jersey', 'Jersey'), ('Shirt', 'Shirt'), ('Shorts', 'Shorts'), ('Skirt', 'Skirt'), ('Suit', 'Suit'), ('Tracksuit', 'Tracksuit'), ('Trousers', 'Trousers')], max_length=50)),
                ('fabric_type', models.CharField(choices=[('Cotton', 'Cotton'), ('Denim', 'Denim'), ('Leather', 'Leather'), ('Linen', 'Linen'), ('Nylon', 'Nylon'), ('Polyester', 'Polyester'), ('Silk', 'Silk'), ('Wool', 'Wool')], max_length=50)),
                ('fabric_m', models.FloatField()),
                ('price_per_m', models.FloatField()),
                ('material_cost', models.FloatField()),
                ('labour_cost', models.FloatField(default=0)),
                ('overhead_cost', models.FloatField(default=0)),
                ('total_cost', models.FloatField()),
                ('label', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estimates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
